name: beiersdorf
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - jupyterlab
  - matplotlib
  - pillow
  - python=3.6
  - requests
  - wordcloud
  - numpy
  - pandas
  - seaborn
  - holoviews


